package com.haloce.tcg.core.event;

public enum EventType {
    GAME_STARTED, ROUND_STARTED, TURN_STARTED,
    PHASE_DRAW_RECHARGE_STARTED, PHASE_DRAW_RECHARGE_ENDED,
    PHASE_DEPLOYMENT_STARTED, PHASE_DEPLOYMENT_ENDED,
    PHASE_SKIRMISH_STARTED, PHASE_SKIRMISH_ENDED,
    PHASE_ENDSTEP_STARTED, PHASE_ENDSTEP_ENDED,
    TURN_ENDED, ROUND_ENDED, GAME_ENDED,

    CARD_DRAWN, SUPPLY_CAP_INCREASED, SUPPLY_REFILLED, BATTERY_GENERATED, RESOURCE_SPENT,
    CARD_PLAY_DECLARED, CARD_PLAY_VALIDATED, CARD_PLAY_REJECTED, UNIT_DEPLOYED, ARMORY_ATTACHED,
    FIELD_ACTIVATED, UNIT_MOVED, UNIT_REPOSITIONED, ORBITAL_LOAD_QUEUED, ORBITAL_DROP_RESOLVED,

    ATTACK_DECLARED, TARGET_LOCKED, HIT_ROLL_RESOLVED, DAMAGE_CALC_STARTED,
    COVER_MITIGATED, DAMAGE_MODIFIED, SHIELD_DAMAGED, HULL_OR_HEALTH_DAMAGED,
    DAMAGE_DEALT, LETHAL_CHECKED, KILL_OCCURRED, OVERKILL_APPLIED, COMBAT_EXCHANGED,

    STATUS_APPLIED, STATUS_REFRESHED, STATUS_STACKED, STATUS_EXPIRED,
    KEYWORD_GAINED, KEYWORD_LOST, PLASMA_TAG_APPLIED, HEADSHOT_TRIGGERED,
    INFECT_TRIGGERED, EMP_APPLIED, CAMO_BROKEN, HIJACK_EXECUTED,

    ORBITAL_STRIKE_DECLARED, ORBITAL_STRIKE, ORBITAL_STRIKE_MISSED,
    POINT_DEFENSE_INTERCEPTED, TARGET_PAINTED, AA_FIRE_RESOLVED,
    CAPITAL_SHIP_DESTROYED, CAPITAL_SHIP_CRASH_RESOLVED,
    GALACTIC_EVENT_ROLLED, GALACTIC_EVENT,

    LANE_CONTROL_UPDATED, OBJECTIVE_PROGRESS_UPDATED, OBJECTIVE_COMPLETED,
    BASE_DAMAGED, PLAYER_ELIMINATED, WIN_CONDITION_MET
}
