package com.haloce.tcg.core.event;

public enum EventType {
    GAME_STARTED, ROUND_STARTED, TURN_STARTED,
    PHASE_DRAW_RECHARGE_STARTED, PHASE_DRAW_RECHARGE_ENDED,
    PHASE_DEPLOYMENT_STARTED, PHASE_DEPLOYMENT_ENDED,
    PHASE_SKIRMISH_STARTED, PHASE_SKIRMISH_ENDED,
    PHASE_ENDSTEP_STARTED, PHASE_ENDSTEP_ENDED,
    TURN_ENDED, ROUND_ENDED, GAME_ENDED,

    CARD_DRAWN, SUPPLY_CAP_INCREASED, SUPPLY_REFILLED, BATTERY_GENERATED, RESOURCE_SPENT,
    CARD_PLAY_DECLARED, CARD_PLAY_VALIDATED, CARD_PLAY_REJECTED, UNIT_DEPLOYED, ARMORY_ATTACHED,
    FIELD_ACTIVATED, UNIT_MOVED, UNIT_REPOSITIONED, ORBITAL_LOAD_QUEUED, ORBITAL_DROP_RESOLVED,

    ATTACK_DECLARED, TARGET_LOCKED, HIT_ROLL_RESOLVED, DAMAGE_CALC_STARTED,
    COVER_MITIGATED, DAMAGE_MODIFIED, SHIELD_DAMAGED, HULL_OR_HEALTH_DAMAGED,
    DAMAGE_DEALT, LETHAL_CHECKED, KILL_OCCURRED, OVERKILL_APPLIED, COMBAT_EXCHANGED,

    STATUS_APPLIED, STATUS_REFRESHED, STATUS_STACKED, STATUS_EXPIRED,
    KEYWORD_GAINED, KEYWORD_LOST, PLASMA_TAG_APPLIED, HEADSHOT_TRIGGERED,
    INFECT_TRIGGERED, EMP_APPLIED, CAMO_BROKEN, HIJACK_EXECUTED,

    ORBITAL_STRIKE_DECLARED, ORBITAL_STRIKE, ORBITAL_STRIKE_MISSED,
    POINT_DEFENSE_INTERCEPTED, TARGET_PAINTED, AA_FIRE_RESOLVED,
    CAPITAL_SHIP_DESTROYED, CAPITAL_SHIP_CRASH_RESOLVED,
    GALACTIC_EVENT_ROLLED, GALACTIC_EVENT,

    LANE_CONTROL_UPDATED, OBJECTIVE_PROGRESS_UPDATED, OBJECTIVE_COMPLETED,
    BASE_DAMAGED, PLAYER_ELIMINATED, WIN_CONDITION_MET,

    DIPLOMACY_RELATION_CHANGED,
    COVENANT_SCHISM_TRIGGERED,
    COVENANT_TRUCE_PROPOSED,
    COVENANT_TRUCE_BROKEN,
    SURVIVAL_PROTOCOL_STARTED,
    SURVIVAL_PROTOCOL_ENDED,
    BETRAYER_MARKED,
    RESOURCE_AID_TRANSFERRED,

    UNSC_COMBINED_ARMS_TRIGGERED,
    UNSC_MORALE_BOOST_APPLIED,
    UNSC_ODST_INSTANT_DROP,
    UNSC_SUPPLY_CRATE_DEPLOYED,
    UNSC_VEHICLE_CORE_SALVAGED,
    UNSC_MAC_FIRED,
    UNSC_COLE_PROTOCOL_TRIGGERED,

    SPARTAN_FREE_MOVE_USED,
    SPARTAN_HIJACK_ATTEMPTED,
    SPARTAN_HIJACK_SUCCEEDED,
    SPARTAN_SOEIV_DROPPED,
    SPARTAN_MIA_ENTERED,
    SPARTAN_MIA_RECOVERED,
    SPARTAN_LAST_STAND_BUFFED,
    
    // Forerunner Events - 先行者事件
    FORERUNNER_MATTER_RECONFIGURED,          // 物质重组：单位死亡返还能量
    FORERUNNER_POWER_LEVEL_INCREASED,        // 能级提升
    SENTINEL_MANUFACTURED,                    // 哨兵制造厂生成Token
    SENTINEL_AUTO_REPAIRED,                   // 哨兵自动修复
    SUPPRESSOR_FIELD_ACTIVATED,               // 抑制器领域激活
    PROMETHEAN_DATA_REMNANT_CREATED,          // 普罗米修斯数据残影生成
    PROMETHEAN_UNIT_REVIVED,                  // 观察者复活骑士
    PROMETHEAN_WATCHER_EJECTED,               // 观察者弹出维修
    PROMETHEAN_CRAWLER_BYPASSED_FRONTLINE,    // 爬行者跳过前排
    HALO_INDEX_COLLECTED,                     // 收集索引器
    HALO_TERMINAL_ACTIVATION_STARTED,         // 终端激活开始
    HALO_PULSE_FIRED,                         // 环带脉冲发射
    HALO_TERMINAL_DESTROYED,                  // 终端被摧毁
    SLIPSPACE_GATE_ESTABLISHED,               // 跃迁门建立
    SLIPSPACE_UNIT_TELEPORTED,                // 单位传送
    GRAVITY_WELL_INTERCEPTED,                 // 重力井拦截空投
    HARDLIGHT_PENETRATION_TRIGGERED,          // 硬光穿透伤害
    HARDLIGHT_SHIELD_LAYERED,                 // 硬光护盾叠加
    LIGHTBLADE_CHARGED,                       // 光刃充能
    COMPOSER_LAB_BUILT,                       // 合成工厂建造
    BIOLOGICAL_DATA_COLLECTED,                // 生物数据收集
    SENTINEL_UPGRADE_STARTED,                 // 哨兵升级开始
    SENTINEL_UPGRADE_COMPLETED,               // 哨兵升级完成
    PROMETHEAN_DIRECT_COMPOSED                // 直接合成普罗米修斯
}
